# https://istio.io/docs/reference/config/networking/v1alpha3/gateway/
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: quotes-gateway
  namespace: storage-quotes
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
# https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: quotes
  namespace: storage-quotes
  labels:
    app: quotes
spec:
  hosts:
  - "*"
  gateways:
  - quotes-gateway
  http:
  - route:
    - destination:
        host: quotes
        port:
          number: 80
    match:
    - uri:
        exact: /quotes

---
# https://istio.io/docs/reference/config/networking/v1alpha3/virtual-service/
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: googleapis
  namespace: storage-quotes
  labels:
    app: quotes
spec:
  hosts:
    - '*.googleapis.com'
  tls:
    - match:
        - port: 443
          sniHosts:
            - '*.googleapis.com'
      route:
        - destination:
            host: '*.googleapis.com'
            port:
              number: 443

---
# https://istio.io/docs/reference/config/networking/v1alpha3/service-entry/#ServiceEntry
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: googleapis
  namespace: storage-quotes
  labels:
    app: quotes
spec:
  hosts:
  - "*.googleapis.com"
  ports:
  - number: 443
    name: tls-googleapis
    protocol: TLS
  resolution: NONE
  location: MESH_EXTERNAL
